name: Convert
description: Convert to avif

runs:
  using: composite
  steps:
    - name: Install Imagemagick
      shell: bash
      run: sudo apt-get install -y imagemagick

    - name: Go to images
      shell: bash
      run: cd images/

    - name: Convert PNG to AVIF
      shell: bash
      run: |
        for file in $(find . -type f -name '*.png'); do
          convert "${file}" "${file%.*}.avif"
        done

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Convert PNG to AVIF
