name: Convert
description: Convert to avif

runs:
  using: composite
  steps:
    - name: Install Imagemagick
      shell: bash
      run: sudo apt-get install -y imagemagick

    - name: Go to images
      shell: bash
      run: cd images/

    - name: Convert PNG to AVIF
      shell: bash
      run: |
        for file in $(find . -type f -name '*.png'); do
          convert -background transparent "${file}" "${file%.*}.avif"
        done
